[package]
name = "methoddb"
version = "1.0.0"
authors = ["sirfuzzalot <57846408+sirfuzzalot@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.10"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features= false
features = ["json"]
